function love.load()
    print("SCHOOL HACK OWO :3 MADE BY A THERIAN AND FURRY OWO :3")
    print("Now exploiting")
    os.execute("echo now running")
    print("Now killing firewall")
    os.execute("tasklist") -- gets process ID (PNID)
    os.execute("taskkill /F /IM cisco.exe /T")
    os.execute("taskkill /F /IM umbrella.exe /T")
    os.execute("taskkill /F /IM umbrellaclient.exe /T")
    print("Now installing software to prevent the school from looking/spying")
    os.execute("winget install MullvadVPN.MullvadBrowser --disable-interactivity")
    os.execute("winget install MullvadVPN.MullVadVPNLoader --disable-interactivity")
    print("Now installing extra software")
    os.execute("winget install ppy.osu --disable-interactivity")
    os.execute("winget install Microsoft.VisualStudioCode --disable-interactivity")
    os.execute("winget install GitHub.GitHubDesktop --disable-interactivity")
    print("Finshed!!")
    print("Made with love and fluffyness!!")
    print("This was made by Drwhomust a therian!")
    print("Join us in the park wearing gear and having fun!")
    print("Hope to see you soon")
    print("now quiting!")
    love.event.quit()
end

function love.draw()
    love.graphics.print("NOW RUNNING EXPOLIT PLEASE WAIT A FEW MINUTES!! THE PROGRAM WILL CLOSE IT SELF WHEN IT IS FINSHED!!", 10, 10)
end